config/routes.rb
Larpwriter::Application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  root to: "pages#home"

  get "support"       => "pages#support"
  get "documentation" => "pages#documentation"
  get "forum"         => "pages#forum"

  resources :larps do
    resources :tags
    resources :groups
    resources :pcs
    resources :npcs
    resources :players
    resources :npc_players
    resources :organizers
    resources :documents
    resources :relationships, only: [] do
      get  :missing,         on: :collection
      post :change_position, on: :member
    end
    resources :memberships, only: [] do
      post :change_position, on: :member
    end
  end

  mount MailsViewer::Engine => '/delivered_mails' if Rails.env.development?
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  include HasAttachedPicture, IsSortable

  ranks :rank, with_same: [:origin_id, :origin_type]

  belongs_to :origin, polymorphic: true
  belongs_to :target, polymorphic: true

  before_create :set_larp_id

  # unfortunatelty must be commented
  # see https://github.com/rails/rails/issues/1629#issuecomment-16418737
  # validates_presence_of :origin_id, :origin_type
  validates_presence_of :target_id, :target_type

  # returns relationships whose the reverse relationship (target -> origin) does not exist
  # for instance if we have the relationships (1,2), (2,1), (1,3), (1,4)
  # without_reverse it would return the relationships (1,3), (1,4)
  # because the relationships (3,1), (4,1) do not exist
  def self.without_reverse
    joins(<<-JOIN
            LEFT JOIN relationships r2
              ON  r2.origin_id   = relationships.target_id
              AND r2.origin_type = relationships.target_type
              AND r2.target_id   = relationships.origin_id
              AND r2.target_type = relationships.origin_type
          JOIN
          )
    .where("r2.origin_id IS NULL")
  end

  def picture
    if attached_picture.exists?
      attached_picture
    else
      target.picture
    end
  end

  def reverse_relationship
    Relationship.where(
      origin_id:    target_id,
      origin_type:  target_type,
      target_id:    origin_id,
      target_type:  origin_type
    ).first
  end

  def target_name
    target_custom_name.presence || target.name
  end

  private

  def set_larp_id
    self.larp_id = target.larp_id
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  include IsAssetController

  respond_to :json, only: :change_position

  def missing
    @relationships_without_reverse = @larp.relationships.without_reverse
  end

  def change_position
    relationship = @larp.relationships.find params[:id], lock: true
    relationship.update_position! params[:position]
    head :ok
  end
end

app/views/relationships/_relationship.html.slim
li.well{draggable="true" data-change-position-path="#{change_position_larp_relationship_path @larp, relationship}"}
  - if relationship.picture.exists?
    = image_tag relationship.picture.url(:medium), class: "pull-right img-thumbnail"

  h4= link_to relationship.target_name, [@larp, relationship.target]
  .description= display_description relationship.target_description
  - if relationship.reverse_relationship
    p.small-info= link_to "show/hide the reverse relationship", "#", class: "show-hide-reverse-relationship"
    .description.hidden= display_description relationship.reverse_relationship.target_description
  - else
    p.text-warning.small-info
     span.glyphicon.glyphicon-warning-sign
     |&nbsp;the reverse relationship does not exist

app/views/relationships/_relationships_form_section.html.slim
- unless @larp.pcs.count.zero? and @larp.npcs.count.zero? and @larp.groups.count.zero?
  .nested-fields-section
    = f.simple_fields_for :as_origin_relationships, asset.as_origin_relationships.rank(:rank), html: {novalidate: true} do |as_origin_relationship|
      = render "application/as_origin_relationship_fields", f: as_origin_relationship
    p.links= link_to_add_association "add a new relationship", f, :as_origin_relationships
- else
  p You'll be able to add relationships once you'll have created other PCs, NPCs or groups.

app/views/relationships/_relationships_show_section.html.slim
- if (as_target_relationships_without_reverse = asset.as_target_relationships.without_reverse).any?
  p.text-warning.small-info
    span.glyphicon.glyphicon-warning-sign
    |&nbsp;
    = links_to_assets as_target_relationships_without_reverse.map(&:origin)
    |&nbsp; have a relationship towards #{asset.name} but #{asset.name} has no relationships towards them
- if asset.as_origin_relationships.any?
  ul.sortable-list= render asset.as_origin_relationships.rank(:rank)

app/views/relationships/missing.html.slim
= content_for :html_title, "Missing relationships"

table.table.table-striped.table-hover.table-bordered
  thead
    th From
    th To
  tbody
    - @relationships_without_reverse.each do |relationship|
      tr
        td= link_to relationship.target.name, [@larp, relationship.target]
        td= link_to relationship.origin.name, [@larp, relationship.origin]