config/routes.rb
Larpwriter::Application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  root to: "pages#home"

  get "support"       => "pages#support"
  get "documentation" => "pages#documentation"
  get "forum"         => "pages#forum"

  resources :larps do
    resources :tags
    resources :groups
    resources :pcs
    resources :npcs
    resources :players
    resources :npc_players
    resources :organizers
    resources :documents
    resources :relationships, only: [] do
      get  :missing,         on: :collection
      post :change_position, on: :member
    end
    resources :memberships, only: [] do
      post :change_position, on: :member
    end
  end

  mount MailsViewer::Engine => '/delivered_mails' if Rails.env.development?
end

app/models/group.rb
class Group < ActiveRecord::Base
  include IsAsset, HasAttachedPicture, HasRelationships, IsTaggable, HasDocuments

  has_many :memberships, dependent: :destroy
  accepts_nested_attributes_for :memberships, allow_destroy: true, reject_if: proc { |attributes| attributes['target_id'].blank? }

  # group can be a target in a relationship
  # and target in relationship must respond to `picture`
  def picture
    attached_picture
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  include IsAssetController

  def index
    @groups = @larp.groups.by_name
  end

  def new
    @group = @larp.groups.build
  end

  def create
    @group = @larp.groups.build group_params
    if @group.save
      redirect_to larp_group_path(@larp, @group), notice: "group successfully added!"
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @group.update group_params
      redirect_to larp_group_path(@larp, @group), notice: "group successfully edited"
    else
      render :edit
    end
  end

  def destroy
    @group.destroy!
    redirect_to larp_groups_path(@larp), notice: "group '#{@group.name}' successfully removed"
  end

  private

  def get_asset # rubocop:disable AccessorMethodName
    @group = @larp.groups.find params[:id]
  end

  def group_params
    params[:group].permit(:name, :tags_string, :description, :attached_picture, :remove_attached_picture, memberships_attributes: [:target_id, :target_type, :target_description, :_destroy, :id, :target_custom_name, :attached_picture, :remove_attached_picture], as_origin_relationships_attributes: [:target_id, :target_type, :target_description, :target_custom_name, :_destroy, :id, :attached_picture, :remove_attached_picture], asset_documents_attributes: [:document_id, :_destroy, :id])
  end
end

app/views/groups/_form.html.slim
.panel.panel-default.panel-asset
  .panel-body
    = simple_form_for [@larp, @group] do |f|
      = render "nav", hide_empty_tabs: false

      .tab-content.tab-content-asset
        #infos.tab-pane.active
          = f.input :name, autofocus: true

          = tags_input f

          = f.input :attached_picture, label: "Picture"
          - if @group.attached_picture.exists?
            = f.check_box :remove_attached_picture
            |&nbsp;Remove existing picture

          = render "application/included_documents_form_section", asset: @group, f: f

        #description.tab-pane
          = f.input :description, label: false, input_html: { class: "tinymce" }

        #members.tab-pane
          - if @larp.pcs.any? or @larp.npcs.any?
            .nested-fields-section
              = f.simple_fields_for :memberships, @group.memberships.rank(:rank), html: {novalidate: true} do |membership|
                = render "membership_fields", f: membership
              p.links= link_to_add_association "add a new member", f, :memberships
          - else
            p You'll be able to add members once you'll have created PCs or NPCs.

        #relationships.tab-pane
          = render "relationships/relationships_form_section", f: f, asset: @group

        = f.button :submit, class: "btn btn-info"

app/views/groups/_membership_fields.html.slim
// required: false else we have this error/bug:
// http://stackoverflow.com/questions/7168645/invalid-form-control-only-in-google-chrome
.nested-fields.well
  = link_to_remove_association "remove this member", f, class: "pull-right remove-association", data: {confirm: "Are you sure?"}

  = f.input :target_type,  required: false, collection: ["Pc", "Npc"],       input_html: {data: {role: "target-type-selector"}}, selected: "#{f.object.target_type.presence || 'Pc'}"
  = f.association :target, required: false, collection: @larp.pcs.by_name,  input_html: {data: {role: "target-selector", "target-type" => "Pc"}}
  = f.association :target, required: false, collection: @larp.npcs.by_name, input_html: {data: {role: "target-selector", "target-type" => "Npc"}}

  = f.input :target_description

  p.small-info= link_to "show/hide options", "#", class: "show-hide-options"
  .options.hidden
    = f.input :target_custom_name, hint: "Fill in this field only if you want to display a specific name instead of the pc or npc official name"
    = f.input :attached_picture, label: "Target custom picture", hint: "Upload a file only if you want to display a specific picture instead of the target official picture"
    - if f.object.attached_picture.exists?
      = f.check_box :remove_attached_picture
      |&nbsp;Remove existing picture

app/views/groups/_nav.html.slim
ul.nav.nav-tabs
  li.active
    a href="#infos" data-toggle="tab" Infos
  - unless hide_empty_tabs && @group.description.blank?
    li
      a href="#description" data-toggle="tab" Description
  - unless hide_empty_tabs && @group.memberships.count.zero?
    li
      a href="#members" data-toggle="tab" Members (#{@group.memberships.count})
  - unless hide_empty_tabs && @group.as_origin_relationships.count.zero?
    li
      a href="#relationships" data-toggle="tab" Relationships (#{@group.as_origin_relationships.count})

app/views/groups/index.html.slim
= content_for :html_title, "Groups"

= content_for :asset_actions
  li.asset-action= link_to "add one", [:new, @larp, :group], class: "btn btn-info btn-xs"

- if @groups.count.zero?
  p There is no groups yet.

- else
  table.table.table-striped.table-hover.table-bordered

    thead
      th Name
      th # members
      th Tags

    tbody
      - @groups.each do |group|
        tr
          td.asset-name
            - if group.picture.exists?
              = image_tag group.picture.url(:thumbnail), class: "img-thumbnail img-thumbnail-in-index"
            = links_to_asset_show_and_edit group
          td= group.memberships_count
          td= display_tags group.tags

app/views/groups/new.html.slim
= content_for :html_title, "Add a new group"
= render "form"

app/views/groups/show.html.slim
= content_for :html_title, @group.name

= content_for :asset_actions
  li.asset-action= link_to "remove", larp_group_path(@larp, @group), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger btn-xs"
  li.asset-action= link_to "edit", edit_larp_group_path(@larp, @group), class: "btn btn-info btn-xs"

.panel.panel-default.panel-asset
  .panel-body
    = render "nav", hide_empty_tabs: true

    .tab-content.tab-content-asset
      #infos.tab-pane.active
        - if @group.attached_picture.exists?
          = image_tag @group.attached_picture.url(:medium), class: "pull-right img-thumbnail"

        label Name
        p= @group.name

        = asset_show_tags_section @group

        = asset_show_included_documents_section @group

      - if @group.description.present?
        #description.tab-pane
          = @group.description.html_safe

      - if @group.memberships.any?
        #members.tab-pane
          ul.sortable-list
            - @group.memberships.rank(:rank).each do |membership|
              li.well{draggable="true" data-change-position-path="#{change_position_larp_membership_path @larp, membership}"}
                - if membership.picture.exists?
                  = image_tag membership.picture.url(:medium), class: "pull-right img-thumbnail"
                h4= link_to membership.target_name, [@larp, membership.target]
                .description= simple_format membership.target_description

      - if @group.as_origin_relationships.any?
        #relationships.tab-pane
          = render "relationships/relationships_show_section", asset: @group