config/routes.rb
Larpwriter::Application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  root to: "pages#home"

  get "support"       => "pages#support"
  get "documentation" => "pages#documentation"
  get "forum"         => "pages#forum"

  resources :larps do
    resources :tags
    resources :groups
    resources :pcs
    resources :npcs
    resources :players
    resources :npc_players
    resources :organizers
    resources :documents
    resources :relationships, only: [] do
      get  :missing,         on: :collection
      post :change_position, on: :member
    end
    resources :memberships, only: [] do
      post :change_position, on: :member
    end
  end

  mount MailsViewer::Engine => '/delivered_mails' if Rails.env.development?
end

app/models/document.rb
class Document < ActiveRecord::Base
  include IsAsset, IsTaggable

  has_many :asset_documents, dependent: :destroy
  accepts_nested_attributes_for :asset_documents, allow_destroy: true, reject_if: proc { |attributes| attributes['documentable_id'].blank? }

  has_attached_file :file
  validates_attachment_size :file, less_than: 20.megabytes, message: "must be less than 20 MB"
  do_not_validate_attachment_file_type :file
  attr_accessor :remove_file
  before_save { |document| document.file = nil if remove_file }
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  include IsAssetController

  def index
    @documents = @larp.documents.by_name
  end

  def new
    @document = @larp.documents.build
  end

  def create
    @document = @larp.documents.build document_params
    if @document.save
      redirect_to larp_document_path(@larp, @document), notice: "document successfully added!"
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @document.update document_params
      redirect_to larp_document_path(@larp, @document), notice: "document successfully edited"
    else
      render :edit
    end
  end

  def destroy
    @document.destroy!
    redirect_to larp_documents_path(@larp), notice: "document '#{@document.name}' successfully removed"
  end

  private

  def get_asset # rubocop:disable AccessorMethodName
    @document = @larp.documents.find params[:id]
  end

  def document_params
    params[:document].permit(:name, :tags_string, :content, :is_included_in_all_pcs, :is_included_in_all_npcs, :file, :remove_file, asset_documents_attributes: [:documentable_id, :documentable_type, :_destroy, :id])
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
  def asset_show_included_documents_section asset
    if asset.asset_documents.any?
      content_tag(:label, "Included documents") +
      content_tag(:p, links_to_assets(asset.documents.by_name))
    end
  end
end

app/views/documents/_form.html.slim
= simple_form_for [@larp, @document] do |f|
  = f.input :name, autofocus: true
  = tags_input f
  = f.input :is_included_in_all_pcs
  = f.input :is_included_in_all_npcs

  = f.input :file
  - if @document.file.exists?
    = f.check_box :remove_file
    |&nbsp;Remove existing file #{@document.file_file_name}

  h3 Included in
  .nested-fields-section
    = f.simple_fields_for :asset_documents, @document.asset_documents, html: {novalidate: true} do |asset_document|
      = render "document_asset_document_fields", f: asset_document
    p.links= link_to_add_association "include in another group, PC or NPC", f, :asset_documents, partial: "document_asset_document_fields"

  h3 Content
  = f.input :content, label: false, input_html: { class: "tinymce" }

  = f.button :submit, class: "btn btn-info"

app/views/documents/index.html.slim
= content_for :html_title, "Documents"

= content_for :asset_actions
  li.asset-action= link_to "add one", [:new, @larp, :document], class: "btn btn-info btn-xs"

- if @documents.count.zero?
  p There is no documents yet.

- else
  table.table.table-striped.table-hover.table-bordered

    thead
      th Name
      th File
      th Tags

    tbody
      - @documents.each do |document|
        tr
          td.asset-name= links_to_asset_show_and_edit document
          td
            - if document.file.exists?
              = link_to document.file_file_name, document.file.url
          td= display_tags document.tags

app/views/documents/new.html.slim
= content_for :html_title, "Add a new document"
= render "form"

app/views/documents/show.html.slim
= content_for :html_title, @document.name

= content_for :asset_actions
  li.asset-action= link_to "remove", larp_document_path(@larp, @document), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger btn-xs"
  li.asset-action= link_to "edit", edit_larp_document_path(@larp, @document), class: "btn btn-info btn-xs"

.panel.panel-default.panel-asset
  .panel-body
    label Name
    p= @document.name

    = asset_show_tags_section @document

    - if @document.is_included_in_all_pcs
      label Is included in all PCs

    - if @document.is_included_in_all_npcs
      label Is included in all NPCs

    - if @document.asset_documents.any?
      label Included in
      p= links_to_assets @document.asset_documents.map(&:documentable)

    - if @document.file.exists?
      label File
      p= link_to @document.file_file_name, @document.file.url

    - if @document.content.present?
      label Content
      = @document.content.html_safe