config/routes.rb
Larpwriter::Application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  root to: "pages#home"

  get "support"       => "pages#support"
  get "documentation" => "pages#documentation"
  get "forum"         => "pages#forum"

  resources :larps do
    resources :tags
    resources :groups
    resources :pcs
    resources :npcs
    resources :players
    resources :npc_players
    resources :organizers
    resources :documents
    resources :relationships, only: [] do
      get  :missing,         on: :collection
      post :change_position, on: :member
    end
    resources :memberships, only: [] do
      post :change_position, on: :member
    end
  end

  mount MailsViewer::Engine => '/delivered_mails' if Rails.env.development?
end

app/models/tag.rb
require 'html/sanitizer'
class Tag < ActiveRecord::Base
  SANITIZER = HTML::FullSanitizer.new

  include IsAsset

  has_many :taggings, dependent: :destroy

  has_many :groups,      through: :taggings, source: :taggable, source_type: "Group"
  has_many :pcs,         through: :taggings, source: :taggable, source_type: "Pc"
  has_many :npcs,        through: :taggings, source: :taggable, source_type: "Npc"
  has_many :players,     through: :taggings, source: :taggable, source_type: "Player"
  has_many :npc_players, through: :taggings, source: :taggable, source_type: "NpcPlayer"
  has_many :organizers,  through: :taggings, source: :taggable, source_type: "Organizer"
  has_many :documents,   through: :taggings, source: :taggable, source_type: "Document"

  before_validation :set_color, on: :create, unless: :color
  before_validation :sanitize_name, if: :name_changed?

  validates_format_of :color, with: /\A#(?:[0-9a-fA-F]{3}){1,2}\z/

  private

  def sanitize_name
    self.name = SANITIZER.sanitize name
  end

  def set_color
    self.color = %w(#F09EA4 #F3ECDC #B8DC23 #C797BF #8DD4F4 #95B2DE #D5E1A0 #97CA9F #F9CD90 #FEF59E).sample
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  include IsAssetController

  def index
    redirect_to @larp
  end

  def show
  end

  def edit
  end

  def update
    if @tag.update tag_params
      redirect_to larp_tag_path(@larp, @tag), notice: "tag successfully edited"
    else
      render :edit
    end
  end

  def destroy
    @tag.destroy!
    redirect_to larp_tags_path(@larp), notice: "tag '#{@tag.name}' successfully removed"
  end

  private

  def get_asset # rubocop:disable AccessorMethodName
    @tag = @larp.tags.find params[:id]
  end

  def tag_params
    params[:tag].permit(:name, :description,  :color)
  end
end

app/helpers/tags_helper.rb
module TagsHelper
  def asset_show_tags_section asset
    if asset.tags.any?
      content_tag(:label, "Tags") + content_tag(:p, display_tags(asset.tags))
    end
  end

  def display_tags tags, with_line_breaks: false, with_count: false
    tags.by_name.map do |tag|
      link_to [@larp, tag], class: "tag" do
        tag_span tag, with_count: with_count
      end
    end.join("#{'<br />' if with_line_breaks}").html_safe
  end

  def tag_span tag, with_count: false
    content = tag.name
    content +=  " " + content_tag(:span, tag.taggings_count, class: "badge badge-tag-count") if with_count
    content_tag :span, content.html_safe, class: "label", style: "background-color: #{tag.color}"
  end

  def tags_input form
    hint = "to add a tag, type its name and press RETURN"
    hint += " ; <a href='#' id='see-tags' data-content='#{display_tags @larp.tags, with_line_breaks: true}'>see existing tags</a>" if @larp.tags.any?
    form.input :tags_string, label: "Tags", hint: hint.html_safe, input_html: { data: { role: "tagsinput" } }
  end
end

app/views/tags/_form.html.slim
= simple_form_for [@larp, @tag] do |f|
  = f.input :name, autofocus: true

  = f.input :color, input_html: { class: "colorpicker-input" }

  = f.input :description

  = f.button :submit, class: "btn btn-info"

app/views/tags/edit.html.slim
= render "application/asset_edit"

app/views/tags/show.html.slim
= content_for :html_title, @tag.name

= content_for :asset_actions
  li.asset-action= link_to "remove", larp_tag_path(@larp, @tag), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger btn-xs"
  li.asset-action= link_to "edit", edit_larp_tag_path(@larp, @tag), class: "btn btn-info btn-xs"

.panel.panel-default.panel-asset
  .panel-body
    label Name
    p= tag_span @tag

    - if @tag.description.present?
      label Description
      = simple_format @tag.description

    - if @tag.taggings.any?
      label= pluralize @tag.taggings.count, "tagged item"
      table.table.table-striped.table-hover.table-bordered
        tbody
          - Larp::PLURAL_ASSET_TYPES.each do |plural_asset_type|
            - tag_count = @tag.send(plural_asset_type).count
            - unless tag_count.zero?
              tr
                td= pluralize tag_count, plural_asset_type.to_s.chop
                td= links_to_assets @tag.send(plural_asset_type).by_name